name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build and Package
      run: |
        echo "Building the application..."
        # Example: Python packaging
        # If using Docker, replace this with Docker build
        python setup.py install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        slot-name: 'production'  # Optional, if using deployment slots
        package: .
        resource-group-name: ${{ secrets.AZURE_RESOURCE_GROUP }}
      
    - name: Verify Deployment
      run: |
        echo "Verifying deployment..."
        curl https://${{ secrets.AZURE_APP_NAME }}.azurewebsites.net || echo "Application may take time to start"
